import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/main.scss";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { SessionProvider } from "next-auth/react"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Farmacia Heguilen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body>
        <SessionProvider>
        <Header />
        {children}
        <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
